- name: install nginx and start
  hosts: local
  connection: local
  become: true
  tasks: 
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
    register: output

  - name: check installed or not
    ansible.builtin.debug:
      msg: "nginx installed"
    when: output.rc == 0

