- name: play-01
  hosts: local
  connection: local
  tasks:
  - name: play-01 and task-01
    ansible.builtin.debug:
      msg: "Hello, play01 task01"
    
  - name: play-01 and task-02
    ansible.builtin.debug:
      msg: "Hello, play01 task02"

- name: play-02
  hosts: local
  connection: local
  tasks:
  - name: play-02 and task-01
    ansible.builtin.debug:
      msg: "Hello, play02 task01"
    
  - name: play-02 and task-02
    ansible.builtin.debug:
      msg: "Hello, play02 task02"