- name: varibles from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: enter your name
    private: false
  tasks:
  - name: print credentials
    ansible.builtin.debug:
     msg: "username is : {{ username }}"
     