- name: varibles from inventory
  hosts: front
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
     msg: "course name is: {{ COURSE }}, Trainer is {{ Trainer}}"
     